=== gentlegiantJGC/Minecraft-Universal-Block-Mappings/compiler/format_specification/json_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://raw.githubusercontent.com/gentlegiantJGC/Minecraft-Universal-Conversion-Mappings/master/compiler/format_specification/json_schema.json",
	"definitions": {
		"specification": {
			"type": "object",
			"properties": {
				"properties": {
					"type": "object",
					"additionalProperties": {
						"type": "array",
						"items": {
							"type": "string"
						}
					}
				},
				"defaults": {
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				}
			}
		},
		"mapping_functions": {
			"type": "array",
			"items": {
				"anyOf": [
					{
						"type": "object",
						"properties": {
							"function": {
								"type": "string",
								"pattern": "new_block"
							},
							"options": {
								"type": "string"
							}
						}
					},
					{
						"type": "object",
						"properties": {
							"function": {
								"type": "string",
								"pattern": "new_properties"
							},
							"options": {
								"type": "object",
								"additionalProperties": {
									"type": "string"
								}
							}
						}
					},
					{
						"type": "object",
						"properties": {
							"function": {
								"type": "string",
								"pattern": "map_properties"
							},
							"options": {
								"type": "object",
								"additionalProperties": {
									"type": "object",
									"additionalProperties": {
										"$ref": "#/definitions/mapping_functions"
									}
								}
							}
						}
					},
					{
						"type": "object",
						"properties": {
							"function": {
								"type": "string",
								"pattern": "carry_properties"
							},
							"options": {
								"type": "object",
								"additionalProperties": {
									"type": "array",
									"items": {
										"type": "string"
									}
								}
							}
						}
					},
					{
						"type": "object",
						"properties": {
							"function": {
								"type": "string",
								"pattern": "new_nbt"
							},
							"options": {}
						}
					},
					{
						"type": "object",
						"properties": {
							"function": {
								"type": "string",
								"pattern": "multiblock"
							},
							"options": {
								"anyOf": [
									{
										"type": "object",
										"properties": {
											"coords": {
												"type": "array",
												"items": {
													"type": "integer"
												},
												"minLength": 3,
												"maxLength": 3
											}
										},
										"required": ["coords"],
										"$ref": "#/definitions/mapping_functions"
									},
									{
										"type": "array",
										"items": [
											{
												"type": "object",
												"properties": {
													"coords": {
														"type": "array",
														"items": {
															"type": "integer"
														},
														"minLength": 3,
														"maxLength": 3
													}
												},
												"required": ["coords"],
												"$ref": "#/definitions/mapping_functions"
											}
										]
									}
								]
							}
						}
					},
					{
						"type": "object",
						"properties": {
							"function": {
								"type": "string",
								"pattern": "map_block_name"
							},
							"options": {
								"type": "object",
								"additionalProperties": {
									"$ref": "#/definitions/mapping_functions"
								}
							}
						}
					},
					{
						"type": "object",
						"properties": {
							"function": {
								"type": "string",
								"pattern": "map_input_nbt"
							},
							"options": {}
						}
					},
					{
						"type": "object",
						"properties": {
							"function": {
								"type": "string",
								"pattern": "carry_nbt"
							},
							"options": {}
						}
					},
					{
						"type": "object",
						"properties": {
							"function": {
								"type": "string",
								"pattern": "map_nbt"
							},
							"options": {}
						}
					}
				]
			}
		}
	},
	"type": "object",
	"properties": {
		"specification": {
			"$ref": "#/definitions/specification"
		},
		"to_universal": {
			"$ref": "#/definitions/mapping_functions"
		},
		"from_universal": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/mapping_functions"
			}
		},
		"blockstate_specification": {
			"$ref": "#/definitions/specification"
		},
		"blockstate_to_universal": {
			"$ref": "#/definitions/mapping_functions"
		},
		"blockstate_from_universal": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/mapping_functions"
			}
		}
	}
}

=== gentlegiantJGC/Minecraft-Universal-Block-Mappings/compiler/primitives/blocks/numerical/vanilla/stonebrick.json
{
	"to_universal": [
		{
			"function": "map_properties",
			"options": {
				"block_data": {
					"0": [
						{
							"function": "new_block",
							"options": "universal_minecraft:stone_bricks"
						},
						{
							"function": "new_properties",
							"options": {
								"variant": "normal"
							}
						}
					],
					"1": [
						{
							"function": "new_block",
							"options": "universal_minecraft:stone_bricks"
						},
						{
							"function": "new_properties",
							"options": {
								"variant": "mossy"
							}
						}
					],
					"2": [
						{
							"function": "new_block",
							"options": "universal_minecraft:stone_bricks"
						},
						{
							"function": "new_properties",
							"options": {
								"variant": "cracked"
							}
						}
					],
					"3": [
						{
							"function": "new_block",
							"options": "universal_minecraft:chiseled_stone_bricks"
						}
					]
				}
			}
		}
	],
	"from_universal": {
		"universal_minecraft:stone_bricks": [
			{
				"function": "new_block",
				"options": "minecraft:stonebrick"
			},
			{
				"function": "map_properties",
				"options": {
					"variant": {
						"normal": [
							{
								"function": "new_properties",
								"options": {
									"block_data": "0"
								}
							}
						],
						"mossy": [
							{
								"function": "new_properties",
								"options": {
									"block_data": "1"
								}
							}
						],
						"cracked": [
							{
								"function": "new_properties",
								"options": {
									"block_data": "2"
								}
							}
						]
					}
				}
			}
		],
		"universal_minecraft:chiseled_stone_bricks": [
			{
				"function": "new_block",
				"options": "minecraft:stonebrick"
			},
			{
				"function": "new_properties",
				"options": {
					"block_data": "3"
				}
			}
		]
	},
	"blockstate_specification": {
		"properties": {
			"variant": [
				"normal",
				"cracked",
				"mossy",
				"chiseled"
			]
		},
		"defaults": {
			"variant": "normal"
		}
	},
	"blockstate_to_universal": [
		{
			"function": "map_properties",
			"options": {
				"variant": {
					"normal": [
						{
							"function": "new_block",
							"options": "universal_minecraft:stone_bricks"
						},
						{
							"function": "new_properties",
							"options": {
								"variant": "normal"
							}
						}
					],
					"cracked": [
						{
							"function": "new_block",
							"options": "universal_minecraft:stone_bricks"
						},
						{
							"function": "new_properties",
							"options": {
								"variant": "cracked"
							}
						}
					],
					"mossy": [
						{
							"function": "new_block",
							"options": "universal_minecraft:stone_bricks"
						},
						{
							"function": "new_properties",
							"options": {
								"variant": "mossy"
							}
						}
					],
					"chiseled": [
						{
							"function": "new_block",
							"options": "universal_minecraft:chiseled_stone_bricks"
						}
					]
				}
			}
		}
	],
	"blockstate_from_universal": {
		"universal_minecraft:stone_bricks": [
			{
				"function": "new_block",
				"options": "minecraft:stonebrick"
			},
			{
				"function": "carry_properties",
				"options": {
					"variant": [
						"normal",
						"cracked",
						"mossy"
					]
				}
			}
		],
		"universal_minecraft:chiseled_stone_bricks": [
			{
				"function": "new_block",
				"options": "minecraft:stonebrick"
			},
			{
				"function": "new_properties",
				"options": {
					"variant": "chiseled"
				}
			}
		]
	}
}
