=== gentlegiantJGC/Minecraft-Universal-Block-Mappings/PyMCTCompiler/format_specification/json_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://raw.githubusercontent.com/gentlegiantJGC/Minecraft-Universal-Conversion-Mappings/master/compiler/format_specification/json_schema.json",
	"definitions": {
		"specification": {
			"type": "object",
			"properties": {
				"properties": {
					"type": "object",
					"additionalProperties": {
						"type": "array",
						"items": {
							"type": "string"
						}
					}
				},
				"defaults": {
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				}
			}
		},
		"mapping_functions": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"function": {
						"type": "string",
						"enum": [
							"new_block",
							"new_properties",
							"map_properties",
							"carry_properties",
							"new_nbt",
							"multiblock",
							"map_block_name",
							"walk_input_nbt",
							"carry_nbt",
							"map_nbt"
						]
					},
					"options": {}
				},
				"required": ["function", "options"],
				"additionalProperties": false,
				"oneOf": [
					{
						"if": {
							"properties": {
								"function": {
									"pattern": "new_block"
								}
							}
						},
						"then": {
							"properties": {
								"options": {
									"type": "string"
								}
							}
						}
					},
					{
						"if": {
							"properties": {
								"function": {
									"pattern": "new_properties"
								}
							}
						},
						"then": {
							"properties": {
								"options": {
									"type": "object",
									"additionalProperties": {
										"type": "string"
									}
								}
							}
						}
					},
					{
						"if": {
							"properties": {
								"function": {
									"pattern": "map_properties"
								}
							}
						},
						"then": {
							"properties": {
								"options": {
									"type": "object",
									"additionalProperties": {
										"type": "object",
										"additionalProperties": {
											"$ref": "#/definitions/mapping_functions"
										}
									}
								}
							}
						}
					},
					{
						"if": {
							"properties": {
								"function": {
									"pattern": "carry_properties"
								}
							}
						},
						"then": {
							"properties": {
								"options": {
									"type": "object",
									"additionalProperties": {
										"type": "array",
										"items": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					{
						"if": {
							"properties": {
								"function": {
									"pattern": "new_nbt"
								}
							}
						},
						"then": {
							"properties": {
								"options": {
									"type": "object"
								}
							}
						}
					},
					{
						"if": {
							"properties": {
								"function": {
									"pattern": "multiblock"
								}
							}
						},
						"then": {
							"properties": {
								"options": {
									"oneOf": [
										{
											"type": "object",
											"properties": {
												"coords": {
													"type": "array",
													"items": {
														"type": "integer"
													},
													"minLength": 3,
													"maxLength": 3
												}
											},
											"required": ["coords"],
											"$ref": "#/definitions/mapping_functions"
										},
										{
											"type": "array",
											"items": [
												{
													"type": "object",
													"properties": {
														"coords": {
															"type": "array",
															"items": {
																"type": "integer"
															},
															"minLength": 3,
															"maxLength": 3
														}
													},
													"required": ["coords"],
													"$ref": "#/definitions/mapping_functions"
												}
											]
										}
									]
								}
							}
						}
					},
					{
						"if": {
							"properties": {
								"function": {
									"pattern": "map_block_name"
								}
							}
						},
						"then": {
							"properties": {
								"options": {
									"type": "object",
									"additionalProperties": {
										"$ref": "#/definitions/mapping_functions"
									}
								}
							}
						}
					},
					{
						"if": {
							"properties": {
								"function": {
									"pattern": "walk_input_nbt"
								}
							}
						},
						"then": {
							"properties": {
								"options": {
									"type": "object"
								}
							}
						}
					},
					{
						"if": {
							"properties": {
								"function": {
									"pattern": "carry_nbt"
								}
							}
						},
						"then": {
							"properties": {
								"options": {
									"type": "object"
								}
							}
						}
					},
					{
						"if": {
							"properties": {
								"function": {
									"pattern": "map_nbt"
								}
							}
						},
						"then": {
							"properties": {
								"options": {
									"type": "object"
								}
							}
						}
					}
				]
			}
		}
	},
	"type": "object",
	"properties": {
		"specification": {
			"$ref": "#/definitions/specification"
		},
		"to_universal": {
			"$ref": "#/definitions/mapping_functions"
		},
		"from_universal": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/mapping_functions"
			}
		},
		"blockstate_specification": {
			"$ref": "#/definitions/specification"
		},
		"blockstate_to_universal": {
			"$ref": "#/definitions/mapping_functions"
		},
		"blockstate_from_universal": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/mapping_functions"
			}
		}
	}
}

=== gentlegiantJGC/Minecraft-Universal-Block-Mappings/PyMCTCompiler/primitives/blocks/numerical/vanilla/cauldron/cauldron2_bedrock.json
{
    "to_universal": [
        {
			"function": "new_block",
			"options": "universal_minecraft:cauldron"
		},
		{
			"function": "new_properties",
			"options": {
				"cauldron_liquid": "water"
			}
		},
		{
            "function": "map_properties",
            "options": {
                "block_data": {
                    "0": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "0"
                            }
                        }
                    ],
                    "1": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "0.5"
                            }
                        }
                    ],
                    "2": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "1"
                            }
                        }
                    ],
                    "3": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "1.5"
                            }
                        }
                    ],
                    "4": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "2"
                            }
                        }
                    ],
                    "5": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "2.5"
                            }
                        }
                    ],
                    "6": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "3"
                            }
                        }
                    ],
                    "8": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "0"
                            }
                        }
                    ],
                    "9": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "0.5"
                            }
                        }
                    ],
                    "10": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "1"
                            }
                        }
                    ],
                    "11": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "1.5"
                            }
                        }
                    ],
                    "12": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "2"
                            }
                        }
                    ],
                    "13": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "2.5"
                            }
                        }
                    ],
                    "14": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "3"
                            }
                        }
                    ]
                }
            }
        }
    ],
    "from_universal": {
        "universal_minecraft:cauldron": [
            {
                "function": "new_block",
                "options": "minecraft:cauldron"
            },
            {
				"function": "map_properties",
				"options": {
					"cauldron_liquid": {
						"water": [
							{
								"function": "new_block",
								"options": "minecraft:cauldron"
							},
                            {
                                "function": "map_properties",
                                "options": {
                                    "level": {
                                        "0": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "0"
                                                }
                                            }
                                        ],
                                        "0.5": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "1"
                                                }
                                            }
                                        ],
                                        "1": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "2"
                                                }
                                            }
                                        ],
                                        "1.5": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "3"
                                                }
                                            }
                                        ],
                                        "2": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "4"
                                                }
                                            }
                                        ],
                                        "2.5": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "5"
                                                }
                                            }
                                        ],
                                        "3": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "6"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
						]
					}
				}
			}
        ]
    },
    "blockstate_specification": {
        "properties": {
            "level": [
                "0",
                "0.5",
                "1",
                "1.5",
                "2",
                "2.5",
                "3"
            ]
        },
        "defaults": {
            "level": "0"
        }
    },
    "blockstate_to_universal": [
        {
            "function": "new_block",
            "options": "universal_minecraft:cauldron"
        },
        {
            "function": "carry_properties",
            "options": {
                "level": [
                    "0",
                    "0.5",
                    "1",
                    "1.5",
                    "2",
                    "2.5",
                    "3"
                ]
            }
        },
        {
			"function": "new_properties",
			"options": {
				"cauldron_liquid": "water"
			}
		}
    ],
    "blockstate_from_universal": {
        "universal_minecraft:cauldron": [
            {
                "function": "new_block",
                "options": "minecraft:cauldron"
            },
            {
                "function": "carry_properties",
                "options": {
                    "level": [
                        "0",
                        "0.5",
                        "1",
                        "1.5",
                        "2",
                        "2.5",
                        "3"
                    ]
                }
            },
            {
				"function": "map_properties",
				"options": {
					"cauldron_liquid": {}
				}
			}
        ]
    }
}

=== gentlegiantJGC/Minecraft-Universal-Block-Mappings/PyMCTCompiler/primitives/blocks/numerical/vanilla/grass/grass_bedrock.json
{
	"to_universal": [
		{
			"function": "map_properties",
			"options": {
				"block_data": {
					"0": [
						{
							"function": "new_block",
							"options": "universal_minecraft:plant"
						},
						{
							"function": "new_properties",
							"options": {
								"type": "grass"
							}
						}
					],
					"1": [
						{
							"function": "new_block",
							"options": "universal_minecraft:plant"
						},
						{
							"function": "new_properties",
							"options": {
								"type": "grass"
							}
						}
					],
					"2": [
						{
							"function": "new_block",
							"options": "universal_minecraft:plant"
						},
						{
							"function": "new_properties",
							"options": {
								"type": "fern"
							}
						}
					],
					"3": [
						{
							"function": "new_block",
							"options": "universal_minecraft:plant"
						},
						{
							"function": "new_properties",
							"options": {
								"type": "fern"
							}
						}
					]
				}
			}
		}
	],
	"from_universal": {
		"universal_minecraft:plant": [
			{
				"function": "map_properties",
				"options": {
					"type": {
						"grass": [
							{
								"function": "new_block",
								"options": "minecraft:tallgrass"
							},
							{
								"function": "new_properties",
								"options": {
									"block_data": "1"
								}
							}
						],
						"fern": [
							{
								"function": "new_block",
								"options": "minecraft:tallgrass"
							},
							{
								"function": "new_properties",
								"options": {
									"block_data": "2"
								}
							}
						]
					}
				}
			}
		]
	},
	"blockstate_specification": {
		"properties": {
			"type": [
				"grass",
				"fern"
			]
		},
		"defaults": {
			"type": "grass"
		}
	},
	"blockstate_to_universal": [
		{
			"function": "map_properties",
			"options": {
				"type": {
					"grass": [
						{
							"function": "new_block",
							"options": "universal_minecraft:plant"
						},
						{
							"function": "new_properties",
							"options": {
								"type": "grass"
							}
						}
					],
					"fern": [
						{
							"function": "new_block",
							"options": "universal_minecraft:plant"
						},
						{
							"function": "new_properties",
							"options": {
								"type": "fern"
							}
						}
					]
				}
			}
		}
	],
	"blockstate_from_universal": {
		"universal_minecraft:plant": [
			{
				"function": "map_properties",
				"options": {
					"type": {
						"grass": [
							{
								"function": "new_block",
								"options": "minecraft:tallgrass"
							},
							{
								"function": "new_properties",
								"options": {
									"type": "grass"
								}
							}
						],
						"fern": [
							{
								"function": "new_block",
								"options": "minecraft:tallgrass"
							},
							{
								"function": "new_properties",
								"options": {
									"type": "fern"
								}
							}
						]
					}
				}
			}
		]
	}
}

=== gentlegiantJGC/Minecraft-Universal-Block-Mappings/PyMCTCompiler/primitives/blocks/numerical/vanilla/redstone_ore/redstone_ore.json
{
	"to_universal": [
		{
			"function": "map_properties",
			"options": {
				"block_data": {
					"0": [
						{
							"function": "new_block",
							"options": "universal_minecraft:redstone_ore"
						},
						{
							"function": "new_properties",
							"options": {
								"lit": "\"false\""
							}
						}
					]
				}
			}
		}
	],
	"from_universal": {
		"universal_minecraft:redstone_ore": [
			{
				"function": "map_properties",
				"options": {
					"lit": {
						"\"false\"": [
							{
								"function": "new_block",
								"options": "minecraft:redstone_ore"
							},
							{
								"function": "new_properties",
								"options": {
									"block_data": "0"
								}
							}
						]
					}
				}
			}
		]
	},
	"blockstate_to_universal": [
		{
			"function": "new_block",
			"options": "universal_minecraft:redstone_ore"
		},
		{
			"function": "new_properties",
			"options": {
				"lit": "\"false\""
			}
		}
	],
	"blockstate_from_universal": {
		"universal_minecraft:redstone_ore": [
			{
				"function": "map_properties",
				"options": {
					"lit": {
						"\"false\"": [
							{
								"function": "new_block",
								"options": "minecraft:redstone_ore"
							}
						]
					}
				}
			}
		]
	}
}

=== gentlegiantJGC/Minecraft-Universal-Block-Mappings/PyMCTCompiler/primitives/blocks/numerical/vanilla/cauldron/lava_cauldron_bedrock.json
{
    "to_universal": [
        {
			"function": "new_block",
			"options": "universal_minecraft:cauldron"
		},
		{
			"function": "new_properties",
			"options": {
				"cauldron_liquid": "lava"
			}
		},
		{
            "function": "map_properties",
            "options": {
                "block_data": {
                    "0": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"0\""
                            }
                        }
                    ],
                    "1": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"0.5\""
                            }
                        }
                    ],
                    "2": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"1\""
                            }
                        }
                    ],
                    "3": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"1.5\""
                            }
                        }
                    ],
                    "4": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"2\""
                            }
                        }
                    ],
                    "5": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"2.5\""
                            }
                        }
                    ],
                    "6": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"3\""
                            }
                        }
                    ],
                    "8": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"0\""
                            }
                        }
                    ],
                    "9": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"0.5\""
                            }
                        }
                    ],
                    "10": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"1\""
                            }
                        }
                    ],
                    "11": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"1.5\""
                            }
                        }
                    ],
                    "12": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"2\""
                            }
                        }
                    ],
                    "13": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"2.5\""
                            }
                        }
                    ],
                    "14": [
                        {
                            "function": "new_properties",
                            "options": {
                                "level": "\"3\""
                            }
                        }
                    ]
                }
            }
        }
    ],
    "from_universal": {
        "universal_minecraft:cauldron": [
            {
                "function": "new_block",
                "options": "minecraft:cauldron"
            },
            {
				"function": "map_properties",
				"options": {
					"cauldron_liquid": {
						"lava": [
							{
								"function": "new_block",
								"options": "minecraft:lava_cauldron"
							},
                            {
                                "function": "map_properties",
                                "options": {
                                    "level": {
                                        "\"0\"": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "8"
                                                }
                                            }
                                        ],
                                        "\"0.5\"": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "9"
                                                }
                                            }
                                        ],
                                        "\"1\"": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "10"
                                                }
                                            }
                                        ],
                                        "\"1.5\"": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "11"
                                                }
                                            }
                                        ],
                                        "\"2\"": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "12"
                                                }
                                            }
                                        ],
                                        "\"2.5\"": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "13"
                                                }
                                            }
                                        ],
                                        "\"3\"": [
                                            {
                                                "function": "new_properties",
                                                "options": {
                                                    "block_data": "14"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
						]
					}
				}
			}
        ]
    },
    "blockstate_specification": {
        "properties": {
            "level": [
                "\"0\"",
                "\"0.5\"",
                "\"1\"",
                "\"1.5\"",
                "\"2\"",
                "\"2.5\"",
                "\"3\""
            ]
        },
        "defaults": {
            "level": "\"0\""
        }
    },
    "blockstate_to_universal": [
        {
            "function": "new_block",
            "options": "universal_minecraft:cauldron"
        },
        {
            "function": "carry_properties",
            "options": {
                "level": [
                    "\"0\"",
                    "\"0.5\"",
                    "\"1\"",
                    "\"1.5\"",
                    "\"2\"",
                    "\"2.5\"",
                    "\"3\""
                ]
            }
        },
        {
			"function": "new_properties",
			"options": {
				"cauldron_liquid": "lava"
			}
		}
    ],
    "blockstate_from_universal": {
        "universal_minecraft:cauldron": [
            {
                "function": "new_block",
                "options": "minecraft:cauldron"
            },
            {
                "function": "carry_properties",
                "options": {
                    "level": [
                        "\"0\"",
                        "\"0.5\"",
                        "\"1\"",
                        "\"1.5\"",
                        "\"2\"",
                        "\"2.5\"",
                        "\"3\""
                    ]
                }
            },
            {
				"function": "map_properties",
				"options": {
					"cauldron_liquid": {
						"lava": [
							{
								"function": "new_block",
								"options": "minecraft:lava_cauldron"
							}
						]
					}
				}
			}
        ]
    }
}
